Rare saving issue workaround.
I once saw this error. All I can think is that Bukkit unloaded extra
classes early while disabling the plugin, or Java messed up rarely.

Attempt to workaround the issue by keeping a reference to
ItemSerialization in FlatSaver.

16:30:48 [INFO] [ChestBank] Disabling ChestBank v1.10.3
16:30:48 [SEVERE] Error occurred while disabling ChestBank v1.10.3 (Is it up to date?)
java.lang.NoClassDefFoundError: me/ellbristow/ChestBank/ItemSerialization
	at me.ellbristow.ChestBank.FlatSaver$SaverSyncTask.run(FlatSaver.java:72)
	at me.ellbristow.ChestBank.FlatSaver.close(FlatSaver.java:117)
	at me.ellbristow.ChestBank.ChestBank.onDisable(ChestBank.java:78)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.disablePlugins(CraftServer.java:279)
	at net.minecraft.server.v1_6_R3.MinecraftServer.stop(MinecraftServer.java:345)
	at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:452)
	at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
Caused by: java.lang.ClassNotFoundException: me.ellbristow.ChestBank.ItemSerialization
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	... 11 more